name: gene-ontology
channels:
  - conda-forge
dependencies:
  - conda-forge::networkx=2.2
  - conda-forge::numpy=1.15.3
  - conda-forge::pandas=0.23.4
  - conda-forge::python=3.6.7
  - conda-forge::requests=2.20.0
  - conda-forge::notebook=5.7.0
  - conda-forge::nbconvert=5.4.0
  - conda-forge::ipykernel=5.1.0
  - pip:
    - obonet==0.2.3
